---
# tasks file for devs
- name: Ensure Apps is installed
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - default-jdk
    - git
    - maven

- name: Clone boxfuse from git
  git:
    repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    dest: "{{ box_path }}"
- name: Make WAR file
  shell:
    cmd: mvn -f {{ box_path }}/pom.xml package