---
# tasks file for prods

- name: Ensure Apps is installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - default-jdk
    - tomcat9
- name: Clean tomcat dir
  file:
    path: {{ tomcat_path }}/ROOT
    state: absent
- name: Pull WAR File
  synchronize:
    src: {{ box_path }}/hello-1.0.war
    dest: {{ tomcat_path }}/ROOT.war
  delegate_to: 10.129.0.31
  notify:
    - restart tomcat9